// Copyright 2023 YMGWorks (@YMGWorks)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define MASTER_LEFT

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED
#define POINTING_DEVICE_ROTATION_180
//#define POINTING_DEVICE_ROTATION_180_RIGHT
#define POINTING_DEVICE_INVERT_X_LEFT
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 3
#define AUTO_MOUSE_TIME 500

#define MOUSE_EXTENDED_REPORT
#define WHEEL_EXTENDED_REPORT
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE

#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN GP4
#define PMW33XX_CS_PIN GP5 // SPI CS pin.


#define SPLIT_TRANSACTION_IDS_KB ETE_GET_INFO, ETE_GET_MOTION, ETE_SET_CPI

#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7
#define I2C_DRIVER I2CD1

#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 64

#define RAW_USAGE_PAGE 0xFF60
#define RAW_USAGE_ID   0x61