POINTING_DEVICE_SPLITS += yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball
I2C_DRIVER_REQUIRED = yes

#ifndef PIMORONI_TRACKBALL_TIMEOUT
#    define PIMORONI_TRACKBALL_TIMEOUT 400
#endif


ENCODER_ENABLE = yes
MOUSEKEY_ENABLE = yes
