// Copyright 2023 YMGWorks (@YMGWorks)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define MASTER_LEFT

#ifdef POINTING_DEVICE_ENABLE
  #define SPLIT_POINTING_ENABLE
  #define POINTING_DEVICE_COMBINED
  #define I2C_DRIVER I2CD1
  #define I2C1_SDA_PIN GP6
  #define I2C1_SCL_PIN GP7

  #define MOUSE_EXTENDED_REPORT
  #define WHEEL_EXTENDED_REPORT
  #define POINTING_DEVICE_HIRES_SCROLL_ENABLE
  
  #define PIMORONI_TRACKBALL_SCALE 6
  #define POINTING_DEVICE_TASK_THROTTLE_MS 1
  #define POINTING_DEVICE_ROTATION_180_RIGHT//左手スクロール・右手カーソルの場合は_RIGHTを末尾に追加
  #define POINTING_DEVICE_INVERT_X
  //#define POINTING_DEVICE_INVERT_X_RIGHT
  #define POINTING_DEVICE_AUTO_MOUSE_ENABLE
  #define AUTO_MOUSE_DEFAULT_LAYER 3
  #define AUTO_MOUSE_TIME 650
#endif

#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 64

#define SPLIT_TRANSACTION_IDS_KB ETE_GET_INFO, ETE_GET_MOTION, ETE_SET_CPI

#define RAW_USAGE_PAGE 0xFF60
#define RAW_USAGE_ID   0x61