// Copyright 2023 YMGWorks (@YMGWorks)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once


//#define SPLIT_POINTING_ENABLE
//#define POINTING_DEVICE_COMBINED
#define POINTING_DEVICE_ROTATION_180
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 3
#define AUTO_MOUSE_TIME 500

//#define SPI_SCK_PIN GP2
//#define SPI_MOSI_PIN GP3
//#define SPI_MISO_PIN GP4
//#define PMW3360_CS_PIN GP5 // SPI CS pin.




//#define SPLIT_TRANSACTION_IDS_KB ETE_GET_INFO, ETE_GET_MOTION, ETE_SET_CPI


// I2C ピン設定 (例: RP2040 Zero の GP4 = SDA, GP5 = SCL)

#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7
#define I2C_DRIVER I2CD1

#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 64

#define RAW_USAGE_PAGE 0xFF60
#define RAW_USAGE_ID   0x61

//#define F_SCL 400000