// Copyright 2023 YMGWorks (@YMGWorks)
// SPDX-License-Identifier: GPL-2.0-or-later

#define SERIAL_USART_PIN_SWAP

#pragma once

#ifdef POINTING_DEVICE_ENABLE
  #define SPLIT_POINTING_ENABLE
  #define POINTING_DEVICE_COMBINED
  #define PIMORONI_TRACKBALL_SCALE 6
  #define POINTING_DEVICE_TASK_THROTTLE_MS 1
  #define POINTING_DEVICE_ROTATION_180
  #define POINTING_DEVICE_AUTO_MOUSE_ENABLE
  #define AUTO_MOUSE_DEFAULT_LAYER 3
  #define AUTO_MOUSE_TIME 650

  #define I2C_DRIVER I2CD1
  #define I2C1_SDA_PIN GP6
  #define I2C1_SCL_PIN GP7

#define SPLIT_USB_DETECT

#endif