// Copyright 2023 YMGWorks (@YMGWorks)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define MASTER_LEFT

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED
//#define POINTING_DEVICE_RIGHT
// pointing device
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 3
#define AUTO_MOUSE_TIME 500
//#define AZOTEQ_IQS5XX_TPS43 1
#define AZOTEQ_IQS5XX_WIDTH_MM 30
#define AZOTEQ_IQS5XX_HEIGHT_MM 30
#define F_SCL 100000

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7

#define MOUSE_EXTENDED_REPORT
#define WHEEL_EXTENDED_REPORT
//#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
//#define POINTING_DEVICE_HIRES_SCROLL_MULTIPULIER 120
//#define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 0

#define SPLIT_TRANSACTION_IDS_KB ETE_GET_INFO, ETE_GET_MOTION, ETE_SET_CPI